title: Qiyuan Zhao
description: My Personal Blog
author: QIYUAN ZHAO
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/zhaoqiyuan1994
about: Freelance developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: zhaoqiyuan1994
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
